imports:
  - { resource: services-doctrine.yml }

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    symfony_live.pos.handler.return_product:
        class: SymfonyLive\Pos\Returns\ReturnProductHandler
        arguments: ["@symfony_live.pos.returns"]

    symfony_live.pos.handler.refund_for_cash:
        class: SymfonyLive\Pos\Returns\RefundForCashHandler
        arguments: ["@symfony_live.pos.returns"]

    symfony_live.pos.handler.refund_for_credit:
        class: SymfonyLive\Pos\Returns\RefundForCreditHandler
        arguments: ["@symfony_live.pos.returns"]

    symfony_live.pos.command_bus:
        class: SymfonyLive\Infrastructure\Bus\CommandBus
        arguments:
           - [ @symfony_live.pos.handler.return_product ]

