imports:
  - { resource: services-doctrine.yml }

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    symfony_live.pos.handler.return_product:
        class: SymfonyLive\Pos\Returns\ReturnProductHandler
        arguments:
          - @symfony_live.pos.event_bus
          - @symfony_live.pos.returns

    symfony_live.pos.event_bus:
        class: SymfonyLive\Infrastructure\Bus\EventBus
        arguments:
          - [ @symfony_live.pos.read_model.outstanding_returns_listener ]

    symfony_live.pos.command_bus:
        class: SymfonyLive\Infrastructure\Bus\CommandBus
        arguments:
          - [ @symfony_live.pos.handler.return_product ]

    symfony_live.pos.read_model.outstanding_returns_listener:
        class: SymfonyLive\Pos\ReadModel\Returns\OutstandingReturnListener
        arguments:
          - @symfony_live.pos.read_model.outstanding_returns

